### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by SpecialAgent45954** [BSData/chronopia#1]
### Reference contact

@amis92 @Chronopia

### Your Discord

SpecialAgent45954

### Additional information

Hello, please, enable me on this system. I helped @Chronopia with the first version of the files, and my help may be needed for maintenance in the future

**Comment by Mad-Spy** [comment]
@Chronopia, can you comment to say this is ok?

**Comment by Chronopia** [comment]
Yes, of course it is ok.

**Comment by Mad-Spy** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/3868546772)
:robot: Invited @SpecialAgent45954 with **push** access. Invite can be accepted on https://github.com/BSData/chronopia/invitations

**Comment by Mad-Spy** [comment]
Just a note to say that your uploaded files should be in the cat format, not the catz format. The release process will create the catz.
